# Generated by Django 2.1.1 on 2018-09-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='active',
        ),
    ]
